### ISSUE TITLE
As a user I should be able to view project tasks grouped by sprints

### ISSUE THREAD

**Issue by ghost** [Biscode/yard#15]

**Comment by ghost** [comment]
@AhmedZaleh @omaromar94 @sherif-ihab @martinnabil @nohaelshourbagy @HAAKS please review

**Comment by nohaelshourbagy** [comment]
please fix the indentation. @MohamedIhab

**Comment by Random-User-2** [comment]
@MohamedIhab your controllers are missing documentation,

**Comment by ghost** [comment]
@nohaelshourbagy I fixed the indentation
@sherif-ihab I added the documentation

**Comment by nohaelshourbagy** [comment]
The def's in the sprints_controller are not indented right, please fix them. @MohamedIhab

**Comment by ghost** [comment]
@nohaelshourbagy fixed them.

**Comment by nohaelshourbagy** [comment]
The" def" and its "end", should have the same indentation. @MohamedIhab

**Comment by ghost** [comment]
@nohaelshourbagy done.

**Comment by HAAKS** [comment]
Add the attr. points to the sprint @MohamedIhab

**Comment by ghost** [comment]
@MohamedIhab Please fix your schema as commented here
https://github.com/Biscode/yard/commit/ac0519919c4fd50dac1621d589f16f03da65a103

**Comment by ghost** [comment]
@AhmedZaleh done.

**Comment by ghost** [comment]
@HAAKS done.

**Comment by ghost** [comment]
@sherif-ihab please review the tests
@omaromar94 @HAAKS please review the scenarios and uml
@AhmedZaleh please review the DB

**Comment by ghost** [comment]
@MohamedIhab Very good. How about changing "totalPoints" into float ? We write it as "total_points".

**Comment by ghost** [comment]
@AhmedZaleh I finished the modifications, please review.
