### ISSUE TITLE
As a user i sould be able to sign up ,, log in and log out

### ISSUE THREAD

**Issue by martinnabil** [Biscode/yard#18]

**Comment by martinnabil** [comment]
@MohamedIhab  @AhmedZaleh  @omaromar94  @nohaelshourbagy @HAAKS   please review i am nearly done

**Comment by ghost** [comment]
I'm not a reviewer, I'm the DB owner. If you changed something in the db, mention me.

**Comment by martinnabil** [comment]
Yes i changed i addded new couloms to the user table

**Comment by ghost** [comment]
@martinnabil I have reviewed the migrations and the schema and I found it no different than what we had in sprint 0.

**Comment by martinnabil** [comment]
@AhmedZaleh  check now it is done 
@MohamedIhab  try now i fixed it

**Comment by ghost** [comment]
@martinnabil I have reviewed the schema and the new migration file, please fix the indentation in this file.
![screenshot from 2015-03-25 21 13 23](https://cloud.githubusercontent.com/assets/6087164/6833186/d70537a4-d333-11e4-9bb8-e8c60226a2e7.png)

**Comment by Random-User-2** [comment]
@martinnabil  Add documentation

**Comment by nohaelshourbagy** [comment]
please fix the indentation and stick to the code convention in rails. @martinnabil

**Comment by martinnabil** [comment]
@nohaelshourbagy what do you mean!?!

**Comment by martinnabil** [comment]
@shreif-ihab i am working on it

**Comment by martinnabil** [comment]
@ahmed-zaleh i fixed it

**Comment by nohaelshourbagy** [comment]
Search for rails code conventions. @martinnabil

**Comment by martinnabil** [comment]
@nohaelshourbagy  i am done please check
@sherif-ihab   i am done please check

**Comment by ghost** [comment]
@martinnabil please fix the indentation in this file 20150325132908_create_users.rb

**Comment by nohaelshourbagy** [comment]
@martinnabil  please fix the indentation in the user_controller and Model--> user.rb.

**Comment by omaromar94** [comment]
sequence diagram?

**Comment by nohaelshourbagy** [comment]
@martinnabil  you didn't fix the indentation.

**Comment by martinnabil** [comment]
@nohaelshourbagy @HAAKS  check whay did u removed Documentaion reviewd after @sherif-ihab  has reviewed it and done ?

**Comment by ghost** [comment]
@martinnabil please add documentation to your controller and model

**Comment by martinnabil** [comment]
@MohamedIhab  i allready did check 
![screenshot from 2015-04-08 22 57 36](https://cloud.githubusercontent.com/assets/10799805/7055290/191ff9a4-de4b-11e4-8f7b-6eaf42f89c6b.png)

**Comment by MohamedIhab** [comment]
add  documentation to the rest not just the default documentation

**Comment by ghost** [comment]
@martinnabil add documentation to the rest not just the default documentation

**Comment by martinnabil** [comment]
i added like on the create what is default is what the function does it is usleess to remove it and write the same again

**Comment by ghost** [comment]
@nohaelshourbagy code review this one
