### ISSUE TITLE
As a user, I should be able to create new projects

### ISSUE THREAD

**Issue by Random-User-2** [Biscode/yard#2]

**Comment by nohaelshourbagy** [comment]
@sherif-ihab   please add the documentation for the code

**Comment by nohaelshourbagy** [comment]
![11016602_10206315710830821_586089502_n](https://cloud.githubusercontent.com/assets/10797700/6742224/b50af55e-ce96-11e4-9a49-4a22ad411095.jpg)
@sherif-ihab  Please check the following sample sequence diagram and re-do it.

**Comment by martinnabil** [comment]
please let us know when you are done

**Comment by nohaelshourbagy** [comment]
@sherif-ihab  make sure you fullly understand the sequence diagram , don't just copy the one in the sample . As for the documentation ,i think it should be more formal and clear.

**Comment by nohaelshourbagy** [comment]
@sherif-ihab  Please write a documentation for each action you implemented even if its obvious.

**Comment by Random-User-2** [comment]
@nohaelshourbagy  sure thing
