### ISSUE TITLE
I should be able to choose tasks according to the sprint points

### ISSUE THREAD

**Issue by Random-User-2** [Biscode/yard#32]

**Comment by Random-User-2** [comment]
@AhmedZaleh  @omaromar94  @nohaelshourbagy @martinnabil @MohamedIhab  @HAAKS  please review

**Comment by Random-User-2** [comment]
@MohamedIhab done

**Comment by omaromar94** [comment]
@sherif-ihab please add documentation to your sprint controller

**Comment by ghost** [comment]
@sherif-ihab great :+1:

**Comment by martinnabil** [comment]
PLz add Tests

**Comment by Random-User-2** [comment]
@omaromar94  done
