### ISSUE TITLE
I should see detailed statistics page

### ISSUE THREAD

**Issue by ghost** [Biscode/yard#50]

**Comment by martinnabil** [comment]
PLz add Tests

**Comment by ghost** [comment]
@martinnabil Add tests for what ?!

**Comment by martinnabil** [comment]
@AhmedZaleh  for your task when done

**Comment by ghost** [comment]
@nohaelshourbagy , @MohamedIhab can you review this please.

**Comment by ghost** [comment]
@nohaelshourbagy @MohamedIhab @martinnabil please review this task.
